### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TikoGrig** [odnoklassniki/ok-android-sdk#13]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
       at ru.ok.android.sdk.OkAuthActivity$OAuthWebViewClient.shouldOverrideUrlLoading(OkAuthActivity.java:244)
       at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:342)
       at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:257)
       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(SystemMessageHandler.java)
       at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lintax** [comment]
What is your application you use for authorization and what are the passed arguments?

**Comment by TikoGrig** [comment]
my application called  BlotClub,
and there is arguments that i pass OkAuthType.ANY, OkScope.VALUABLE_ACCESS, OkScope.LONG_ACCESS_TOKEN, OkScope.PHOTO_CONTENT

**Comment by lintax** [comment]
Latest SDK version will just fail the OAUTH in this scenario rather than crash with NPE, however, the causing problem how you succeeded to get redirection to returnUrl with no response is not yet investigated
